name: Development Tests

on:
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '17.2'
      macos-runner: 'macos-14'

  check-approvals:
    runs-on: ubuntu-latest
    outputs:
        reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - name: Determine PR Number
        id: determine-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"

      - name: Check Approvals
        id: reviews
        if: steps.determine-pr.outputs.pull_request_number != ''
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pr_number=${{ steps.determine-pr.outputs.pull_request_number }}
            state=$(gh pr view "$pr_number" \
                    --repo "$GITHUB_REPOSITORY" \
                    --json reviewDecision \
                    --jq '.reviewDecision')
            echo "state=$state" >> "$GITHUB_OUTPUT"

  pre-merge-tests:
    needs: [check-approvals]
    if: needs.check-approvals.outputs.reviews == 'APPROVED' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '16.1'
      macos-runner: 'macos-13-xlarge'
