name: Development Tests

on:
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '17.2'
      macos-runner: 'macos-14'

  check-approvals:
    runs-on: ubuntu-latest
    outputs:
        reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - name: Determine PR Number
        id: determine-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pr_number=$(gh pr list --repo $GITHUB_REPOSITORY --head $GITHUB_REF_NAME --json number --jq ".[0].number" --limit 1)
            if [[ ! -z "$pr_number" ]]; then
              echo "PR number found: $pr_number"
              echo "::set-output name=pr_number::$pr_number"
            else
              echo "No PR number found for branch $GITHUB_REF_NAME"
              echo "::set-output name=pr_number::"
              exit 0

      - name: Check Approvals
        id: reviews
        if: steps.determine-pr.outputs.pr_number != ''
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pr=${{ steps.determine-pr.outputs.pr_number }}
            state=$(gh pr view "$pr" \
                    --repo "$GITHUB_REPOSITORY" \
                    --json reviewDecision \
                    --jq '.reviewDecision')
            echo "state=$state" >> "$GITHUB_OUTPUT"

  pre-merge-tests:
    needs: [check-approvals]
    if: needs.check-approvals.outputs.reviews == 'APPROVED' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '16.1'
      macos-runner: 'macos-13-xlarge'
