name: Development Tests

on:
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '17.2'
      macos-runner: 'macos-14'

  check-approvals:
    runs-on: ubuntu-latest
    outputs:
        reviews: ${{ steps.reviews.outputs.state }}
    permissions: 
        pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Approvals
        id: reviews
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            echo "Extracted branch name: $branch"
            state=$(gh pr view $branch --json reviewDecision --jq '.reviewDecision')
            echo "Review decision state: $state"
            echo "state=$state" >> "$GITHUB_OUTPUT"

  pre-merge-tests:
    needs: [check-approvals]
    if: needs.check-approvals.outputs.reviews == 'APPROVED' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '16.1'
      macos-runner: 'macos-13-xlarge'
